version: "2"
services:
  django:
    container_name: my-django
    build:
      context: .
      dockerfile: Dockerfile
    image: collabuniba/mini-ipip
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/mini-ipip
    ports:
      - "8000:8000"
