version: "2"
services:
  django:
    container_name: mini-ipip_django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_mini-ipip_django
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/mini-ipip
    ports:
      - "8000:8000"
