sqlite:
  host: localhost
  user: root
  passwd: root 
  db: db.sqlite3
email:
  email_from: "collab.uniba@gmail.com"
  passwd: secret
security:
  secret_key: '=-z@=s3n*-dk=j4h9&r9u*ns*(c&o$6(+xv9g4v2sydkm5lk=^'
django-admin-default-credentials:
  username: admin
  passwd: collab-uniba
