database:
  server: mysql
  host: localhost
  user: root
  passwd: root 
  db: mini_ipip_db
email:
  email_from: 'collab.uniba@gmail.com'
  email_host: 'secret'
  email_host_user: "secret"
  email_host_passwd: "secret"
  email_port: secret
security:
  secret_key: secret
django-admin-default-credentials:
  username: admin
  passwd: collab-uniba
